### ISSUE TITLE
Latest pull from master crash

### ISSUE THREAD

**Issue by dyros26** [jitsi/jitsi-meet-electron#196]
app is working on npm start but when installed it crash.

pulled from master
macos mojave 10.14.3 
node v12.16.0
jitsi-meet-electron v1.1.1
no problem when building on windows 10

When running
![Screen Shot 2020-02-13 at 11 48 05 AM](https://user-images.githubusercontent.com/49423503/74399818-0880c700-4e57-11ea-92fa-ecc55e96811a.png)

When building
![Screen Shot 2020-02-13 at 12 06 35 PM](https://user-images.githubusercontent.com/49423503/74400651-8c3bb300-4e59-11ea-9dbb-bd7d78e82ad4.png)

**Comment by saghul** [comment]
What output do you see in the console if you run the electron app from there?

**Comment by dyros26** [comment]
i cant see the console. it only show the crash warning (first image) when start installed app.

**Comment by saghul** [comment]
You can start the app by doing `./Jitsi\ Meet.app/Contents/MacOS/Jitsi\ Meet` on a terminal.

**Comment by dyros26** [comment]
is that for jitsi-meet-electron?

**Comment by dyros26** [comment]
on npm start, the app is working.
but when the installer is created using npm run dist, the app crash at the start.
it only show this:
![74399818-0880c700-4e57-11ea-92fa-ecc55e96811a](https://user-images.githubusercontent.com/49423503/74417625-fbc59880-4e81-11ea-83a5-4b5f3f21474d.png)

**Comment by saghul** [comment]
Again: once installed, run the app from the terminal as I told you.

**Comment by dyros26** [comment]
It says:

(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Trace/BPT trap: 5

**Comment by saghul** [comment]
Plate the entire output please.

**Comment by dyros26** [comment]
this is the output
![Screen Shot 2020-02-13 at 7 52 09 PM](https://user-images.githubusercontent.com/49423503/74432959-76021700-4e9a-11ea-98b8-13c959fb64af.png)

**Comment by saghul** [comment]
I can repro the crash:

```
 lldb ./Jitsi\ Meet.app/Contents/MacOS/Jitsi\ Meet
(lldb) target create "./Jitsi Meet.app/Contents/MacOS/Jitsi Meet"
Current executable set to './Jitsi Meet.app/Contents/MacOS/Jitsi Meet' (x86_64).
(lldb) run
Process 44059 launched: '/Users/saghul/work/jitsi/jitsi-meet-electron/dist/mac/Jitsi Meet.app/Contents/MacOS/Jitsi Meet' (x86_64)
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Process 44059 stopped
* thread #9, name = 'Chrome_IOThread', stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
    frame #0: 0x00000001001a7be3 Electron Framework`___lldb_unnamed_symbol4235$$Electron Framework + 1555
Electron Framework`___lldb_unnamed_symbol4235$$Electron Framework:
->  0x1001a7be3 <+1555>: ud2
    0x1001a7be5 <+1557>: leaq   -0x60(%rbp), %rdi
    0x1001a7be9 <+1561>: callq  0x1023ef6a0               ; ___lldb_unnamed_symbol120841$$Electron Framework
    0x1001a7bee <+1566>: nop
Target 2: (Jitsi Meet) stopped.
```

**Comment by dyros26** [comment]
what do you think is the solution for this?

**Comment by saghul** [comment]
I don't know yet.

**Comment by dyros26** [comment]
I fixed the crash by updating electron-builder to v22.3.2

**Comment by saghul** [comment]
Nice! Could you please send a PR?

**Comment by lixuguang** [comment]
when I build with mac ,and I got this problem ,I realy thought it's my fault, never thought it's electron-builder problem, and now the problem still in the master relase,please fix it .thx

**Comment by Toraih** [comment]
If you don't want to fix it yourself, use ctramnitz's fork to compile on macs, as long the fixes arn't merged into master:
https://github.com/ctramnitz/jitsi-meet-electron

**Comment by saghul** [comment]
We just released version 2.0.0 with this fix included.
